# Новий розділ

In [10]:
#22
#1.Створіть одновимірний масив (вектор) зі значеннями 𝑒𝑥для кожного натурального числа x, починаючи з 1, та виведіть його значення.

import numpy as np

# Визначаємо натуральні числа, починаючи з 1 (наприклад, до 10)
x_values = np.arange(1, 11)

# Створюємо масив зі значеннями e^x
exp_values = np.exp(x_values)

# Виводимо результат
print(exp_values)



[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [24]:
#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами кожного натурального числа, починаючи з 1, та виведіть його значення.

import numpy as np

# Визначаємо натуральні числа від 1 до 9 (всього 9 елементів для матриці 3x3)
x_values = np.arange(1, 10)

# Обчислюємо тангенс для кожного значення
tan_values = np.tan(x_values)

# Формуємо матрицю 3x3
matrix = tan_values.reshape(3, 3)

# Виводимо результат
print(matrix)


[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [22]:
#3.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть непарні числа.

import numpy as np

# Створюємо масив 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 3))

# Виводимо створений масив
print("Створений масив:\n", matrix)

# Якщо треба визначити непарні числа серед дійсних (наприклад, за модулем)
# Перетворимо дійсні числа у цілі та перевіримо їх парність
odd_numbers = matrix[np.abs(matrix % 2) == 1]

# Виводимо непарні числа
print("Непарні числа:\n", odd_numbers)


Створений масив:
 [[-0.48681412 -0.00499882  0.26335923]
 [ 0.88110999 -0.88506069  0.78385069]
 [ 0.56669774  0.61060234  0.79955671]]
Непарні числа:
 []


In [20]:
#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8 до 0.8 та виведіть його значення

import numpy as np

# Створюємо масив 4x4 з випадковими дійсними числами від -0.8 до 0.8
matrix = np.random.uniform(-0.8, 0.8, (4, 4))

# Виводимо створений масив
print("Створений масив:\n", matrix)


Створений масив:
 [[-0.18899117  0.55989388 -0.21918493 -0.53044614]
 [ 0.58730801  0.64100074 -0.12961616 -0.49944901]
 [ 0.16824359 -0.2879526  -0.33775464  0.74584107]
 [ 0.03807333 -0.15541314 -0.26174002 -0.58397143]]


In [13]:
#5.Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

# Створюємо два одновимірних масиви розміром 6, заповнені випадковими цілими числами від 5 до 15
array1 = np.random.randint(5, 16, 6)
array2 = np.random.randint(5, 16, 6)

# Поелементне додавання
addition = array1 + array2

# Поелементне віднімання
subtraction = array1 - array2

# Поелементне множення
multiplication = array1 * array2

# Виводимо результати
print("Перший масив:", array1)
print("Другий масив:", array2)
print("\nРезультат додавання:", addition)
print("Результат віднімання:", subtraction)
print("Результат множення:", multiplication)


Перший масив: [13 15 11 13 10  5]
Другий масив: [ 5 13  8  6  5  7]

Результат додавання: [18 28 19 19 15 12]
Результат віднімання: [ 8  2  3  7  5 -2]
Результат множення: [ 65 195  88  78  50  35]


In [14]:
#6.Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -6 до 6 та знайдіть їх добуток

import numpy as np

# Створюємо дві матриці 4x4, заповнені випадковими цілими числами від -6 до 6
matrix1 = np.random.randint(-6, 7, (4, 4))
matrix2 = np.random.randint(-6, 7, (4, 4))

# Знаходимо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("\nДобуток матриць:\n", product)


Перша матриця:
 [[ 0 -4 -3 -3]
 [-4 -6 -1 -6]
 [-2  3  6  2]
 [ 2 -4  0  6]]
Друга матриця:
 [[-5  5 -4 -2]
 [-1  1  2  3]
 [-6  4  5  5]
 [ 3  0 -3  6]]

Добуток матриць:
 [[ 13 -16 -14 -45]
 [ 14 -30  17 -51]
 [-23  17  38  55]
 [ 12   6 -34  20]]


In [ ]:
#7.Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

import numpy as np

# Створюємо матрицю розміром 3x2, заповнену випадковими цілими числами від 1 до 8
matrix1 = np.random.randint(1, 9, (3, 2))

# Створюємо матрицю розміром 2x2, заповнену випадковими цілими числами від 1 до 8
matrix2 = np.random.randint(1, 9, (2, 2))

# Перемножуємо матриці
product = np.dot(matrix1, matrix2)

# Виводимо результати
print("Перша матриця (3x2):\n", matrix1)
print("Друга матриця (2x2):\n", matrix2)
print("\nДобуток матриць (3x2 * 2x2):\n", product)


In [15]:
#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

import numpy as np

# Створюємо матрицю розміром 3x3, заповнену випадковими цілими числами від 1 до 8
matrix = np.random.randint(1, 9, (3, 3))

# Знаходимо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    inverse_matrix = "Матриця є виродженою і не має оберненої."

# Виводимо результати
print("Створена матриця (3x3):\n", matrix)
print("\nОбернена матриця:\n", inverse_matrix)


Створена матриця (3x3):
 [[6 5 2]
 [4 2 2]
 [7 2 1]]

Обернена матриця:
 [[-0.07692308 -0.03846154  0.23076923]
 [ 0.38461538 -0.30769231 -0.15384615]
 [-0.23076923  0.88461538 -0.30769231]]


In [16]:
#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та транспонуйте її

import numpy as np

# Створюємо матрицю розміром 4x4, заповнену випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (4, 4))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо результати
print("Створена матриця (4x4):\n", matrix)
print("\nТранспонована матриця:\n", transposed_matrix)


Створена матриця (4x4):
 [[ 0.20634308  0.69130939  0.1219875   0.98212677]
 [ 0.25628616 -0.95208056  0.2823372  -0.38122984]
 [ 0.4370861  -0.41808799 -0.71328003 -0.25191244]
 [-0.75799488 -0.53595458 -0.62868396 -0.42136726]]

Транспонована матриця:
 [[ 0.20634308  0.25628616  0.4370861  -0.75799488]
 [ 0.69130939 -0.95208056 -0.41808799 -0.53595458]
 [ 0.1219875   0.2823372  -0.71328003 -0.62868396]
 [ 0.98212677 -0.38122984 -0.25191244 -0.42136726]]


In [17]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицювипадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np

# Створюємо матрицю розміром 3x4, заповнену випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, (3, 4))

# Створюємо вектор розміром 4x1, заповнений випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, (4, 1))

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результати
print("Створена матриця (3x4):\n", matrix)
print("\nСтворений вектор (4x1):\n", vector)
print("\nДобуток матриці на вектор:\n", product)


Створена матриця (3x4):
 [[0.44550168 0.28881903 0.78983617 0.98630638]
 [0.33585292 0.37187349 0.49745852 0.18057009]
 [0.08214232 0.45054706 0.91249385 0.82945073]]

Створений вектор (4x1):
 [[6]
 [2]
 [8]
 [7]]

Добуток матриці на вектор:
 [[16.47348215]
 [ 8.00252325]
 [14.50005392]]


In [18]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор

import numpy as np

# Створюємо матрицю розміром 2x3, заповнену випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (2, 3))

# Створюємо вектор розміром 3, заповнений випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, 3)

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результати
print("Створена матриця (2x3):\n", matrix)
print("\nСтворений вектор (3):\n", vector)
print("\nДобуток матриці на вектор:\n", product)


Створена матриця (2x3):
 [[ 7 10 10]
 [ 2  3 10]]

Створений вектор (3):
 [0.18453481 0.68505919 0.86243672]

Добуток матриці на вектор:
 [16.76670282 11.04861442]


In [19]:
#12.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та знайдіть суму всіх елементів другої матриці.
import numpy as np

# Створюємо дві матриці розміром 3x3, заповнені випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, (3, 3))
matrix2 = np.random.randint(1, 4, (3, 3))

# Знаходимо суму всіх елементів другої матриці
sum_matrix2 = np.sum(matrix2)

# Виводимо результати
print("Перша матриця (3x3):\n", matrix1)
print("\nДруга матриця (3x3):\n", matrix2)
print("\nСума всіх елементів другої матриці:", sum_matrix2)


Перша матриця (3x3):
 [[3 1 1]
 [1 1 1]
 [3 1 1]]

Друга матриця (3x3):
 [[3 3 2]
 [3 1 2]
 [2 2 1]]

Сума всіх елементів другої матриці: 19


In [25]:
#13.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму їх елементів.

import numpy as np

# Створюємо дві матриці розміром 3x3, заповнені випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))

# Знаходимо суму всіх елементів обох матриць
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

# Виводимо результати
print("Перша матриця (3x3):\n", matrix1)
print("\nДруга матриця (3x3):\n", matrix2)
print("\nСума всіх елементів першої матриці:", sum_matrix1)
print("Сума всіх елементів другої матриці:", sum_matrix2)


Перша матриця (3x3):
 [[5 3 5]
 [2 2 4]
 [1 5 2]]

Друга матриця (3x3):
 [[4 1 5]
 [4 4 5]
 [3 2 2]]

Сума всіх елементів першої матриці: 29
Сума всіх елементів другої матриці: 30


In [26]:
#14.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів на головній діагоналі.

import numpy as np

# Створюємо матрицю розміром 3x3, заповнену випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Знаходимо суму елементів на головній діагоналі
diagonal_sum = np.trace(matrix)

# Виводимо результати
print("Створена матриця (3x3):\n", matrix)
print("\nСума елементів на головній діагоналі:", diagonal_sum)


Створена матриця (3x3):
 [[10  2  9]
 [ 7  5  6]
 [ 9  2  3]]

Сума елементів на головній діагоналі: 18


In [27]:
#15.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного стовпця матриці.
import numpy as np

# Створюємо матрицю розміром 3x3, заповнену випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 3))

# Знаходимо добуток елементів кожного стовпця
column_products = np.prod(matrix, axis=0)

# Перетворюємо вектор-рядок в вектор-стовпчик
column_products = column_products.reshape(-1, 1)

# Виводимо результати
print("Створена матриця (3x3):\n", matrix)
print("\nВектор-стовпчик, що містить добуток елементів кожного стовпця:\n", column_products)


Створена матриця (3x3):
 [[-0.2069056  -0.31524367 -0.31150383]
 [-0.602133   -0.18120686 -0.87189166]
 [ 0.01691028  0.35100636  0.11653697]]

Вектор-стовпчик, що містить добуток елементів кожного стовпця:
 [[0.00210676]
 [0.020051  ]
 [0.03165116]]
